### ISSUE TITLE
[SpongeForge & Pixelmon] PetBlocks not spawning (Latest version 7.0.1)

### ISSUE THREAD

**Issue by Peinful** [Shynixn/PetBlocks#134]
29.04 01:55:08 [Server] Server thread/WARN [Sponge]: No entity type is registered for class com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomGroundArmorstand
29.04 01:55:08 [Server] Server thread/WARN [Sponge]: No entity type is registered for class com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomRabbit

These errors are showing in the console, but I'm getting no error logs.

In-game behaviour is when a user selects the PetBlock it goes from Enabled to Disabled even after "Spawning"

Sorry for the lack of logs but there simply aren't any issues/warnings popping up on the console nor in my crash logs.

**Comment by Peinful** [comment]
Issue has been fixed sorry! A permission was typed wrong by an admin!!!!

**Comment by Shynixn** [comment]
Does the pet now spawn for you and stay spawned? As #133 seems to be the same?

**Comment by Dpa1991** [comment]
What did you typo in the permissions? I can't find any typos in mine.

**Comment by Mahavo** [comment]
@Dpa1991 What permissions do you use? I've tried everything including fresh perms and still no luck. I get that error and it then spawns and de-spawns.

I use luckperms and nucleus.

**Comment by Peinful** [comment]
@Shynixn It spawns for some users but not others! Basically I have no idea what the issue is, myself and one other can do the command /petblock toggle and it works but for another (admin rank btw) it doesnt work. Its a super awkward issue that we are troubleshooting.

**Comment by Shynixn** [comment]
I see, I guess it has something todo how each client deals with unknown entities. As mentioned in various comments Forge removes the normal entity registry. Seems like the entity is still not registered correctly in this version. I wanted to avoid an optional forge layer in PetBlocks-Sponge, however with these reports I can no longer ignore it. 

I can offer to release a snapshot in the next few days when anyone of you can give me feedback?

**Comment by Malp12** [comment]
I'd test a snapshot, running into these same errors, willing to try something out.

**Comment by Dpa1991** [comment]
Yeah I was able to get it to work for me but for my friend it spawns & despawns so I have no idea. We both have the same rank & permissions.

I'd also be happy to help test any snapshots. Do you have a discord server or something I can join?

**Comment by Peinful** [comment]
I'd gladly test a snapshot. I'll keep an eye out on sponge.

**Comment by Shynixn** [comment]
I have spent several hours to get it working, however I could not achieve that the entities getrendered. As it's a complex requirement I have created a forum post in the minecraft forge forum to get some help from the community. 

#https://github.com/MinecraftForge/MinecraftForge/issues/4870

Also, it might not work on Minecraft 1.12, however I think there should be a solution....

**Comment by Shynixn** [comment]
As the Forge way seems to be a dead end, I'll take a look if it's possible to register it via Sponge.

**Comment by Shynixn** [comment]
Sorry it seems like I'll need to put this issue on hold until I release PetBlocks for 1.10.2 as it may works there.

**Comment by BrainStone** [comment]
The betblocks also don’t spawn for me on SpongeForge 1.12.2.

**Comment by BrainStone** [comment]
My suggestion then is to add an additional listener with the order of `LAST` that uncancels all spawning events for petblocks, as it's likely some protection plugins that are blocking the spawning.

**Comment by Shynixn** [comment]
@Tollainmear  

Hm... can you try to adjust the tick values of PetBlocks? Go to the config and set pet.age.smallticks to 20.

@BrainStone 

Uncancels all spawning events for PetBlocks...? This could actually work, I'll think about this. I'm not sure but you can also try the same thing as I suggested @Tollainmear .

**Comment by Tollainmear** [comment]
Thanks a lot! @Shynixn That did worked for me, but not in that way, I have change the `small-ticks`, `large-ticks` and `max-tick` all to zero, and pet appeared.
if I modified it in this way(by setting all ticks config to zero), will it cause any issue?

**Comment by BrainStone** [comment]
Yeah, setting everything to 0 seems to work, though it's still quirky, as sometime the pet doesn't spawn, or despawns. But I'll create separate bugs for those.

**Comment by Tollainmear** [comment]
Thanks for help ;)

**Comment by Shynixn** [comment]
Should be fix in 8.1.0.
